server:
  port: 8080

spring:
  application:
    name: lostandfound
  datasource:
    url: jdbc:mysql://localhost:3306/lost_found_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root # 请修改为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
